#!/bin/bash

CONF_FILES_DIR=conf_files

function backup() {
	local fic="$1"

	if [ -d "$HOME/$fic" -a -e "$HOME/$fic" ] ; then 
		mkdir -p "$HOME/$fic"
	elif [ -e "$HOME/$fic" ] ; then
		mkdir -p "$(dirname "$fic")"
		cp "$HOME/$fic" "$fic"
		git add "$fic"
	fi
}

function for_all_input_files() {
        command=$1
        pushd . >/dev/null
        cd "$CONF_FILES_DIR/"
        while read fichier ; do
                $command "$fichier"
        done
        popd . >/dev/null
}

function for_all_conffiles() {
	local command=$1
	pushd . > /dev/null
	cd "$CONF_FILES_DIR/"
	for fichier in $(find) ; do 
		$command "$fichier"
	done
	popd > /dev/null
}
