#!/bin/bash

CONF_FILES_DIR=~/conf/conf_files

function backup() {
	local fic="$1"

	if [ -d "$HOME/$fic" -a -e "$HOME/$fic" ] ; then 
		mkdir -p "$HOME/$fic"
	elif [ -e "$HOME/$fic" ] ; then
		mkdir -p "$(dirname "$fic")"
		cp "$HOME/$fic" "$fic"
		git add "$fic"
	fi
}


function is_metadata() {
	local filename="$1"
	if [[ "$filename" == ./.git/* || \
	       	 "$filename" == "./.git"  || \
	       	 "$filename" == "./.gitignore"  || \
	       	 "$filename" == "./.gitmodules"  || \
	       	 "$filename" == "./README.md" ]] ; then
		return 0
	fi
	return 1

}
function for_all_input_files() {
        command=$1
        pushd . >/dev/null
        cd "$CONF_FILES_DIR/"
        while read fichier ; do
		if ! is_metadata "$fichier"; then
                	$command "$fichier"
		fi
        done
        popd . >/dev/null
}

function for_all_conffiles() {
	local command=$1
	pushd . > /dev/null
	cd "$CONF_FILES_DIR/"
	for fichier in $(find) ; do 
		if ! is_metadata "$fichier"; then
			$command "$fichier"
		fi
	done
	popd > /dev/null
}
