#!/bin/bash

source ./defaults

CONF_FILES_DIR=${CONF_FILES_DIR:-$default_confg_files_store_dir}

function backup() {
	local fic="$1"

	if [ -d "$HOME/$fic" -a -e "$HOME/$fic" ] ; then 
		mkdir -p "$HOME/$fic"
	elif [ -e "$HOME/$fic" ] ; then
		mkdir -p "$(dirname "$fic")"
		cp "$HOME/$fic" "$fic"
		git add "$fic"
	fi
}


function is_metadata() {
	local filename="$1"
	if [[ "$filename" == ./.git/* || \
	       	 "$filename" == "./.git"  || \
	       	 "$filename" == "./.gitignore"  || \
	       	 "$filename" == "./.gitmodules"  || \
	       	 "$filename" == "./README.md" ]] ; then
		return 0
	fi
	return 1

}
function for_all_input_files() {
        command=$1
        pushd . >/dev/null
        cd "$CONF_FILES_DIR/"
        while read fichier ; do
		if ! is_metadata "$fichier"; then
                	$command "$fichier"
		fi
        done
        popd >/dev/null
}

function for_all_conffiles() {
	local command="$1"
	pushd . > /dev/null
	cd "$CONF_FILES_DIR/"
	for fichier in $(find) ; do 
		if ! is_metadata "$fichier"; then
			$command "$fichier"
		fi
	done
	popd > /dev/null
}

function branch_exists(){
	git show-ref --verify --quiet "refs/heads/$1"
	return $?
}
function get_backup_branch_name() {
	echo "$(echo "$(hostname)-$(whoami)")"
}
function exec_in_backup_branch(){
	local command="$1"
	pushd . >/dev/null
	cd "$CONF_FILES_DIR"
	local backup_branch="$(get_backup_branch_name)"

	if ! branch_exists "$backup_branch"; then
		echo "creating branch $backup_branch ..."
		git checkout -b "$backup_branch" 
	else
		git checkout "$backup_branch"
	fi

	$command
	
	popd >/dev/null
}

function exec_in_master_branch(){
	local command="$1"
	pushd . >/dev/null
	cd "$CONF_FILES_DIR"

	git checkout master 

	$command
	
	popd >/dev/null
}
